const HALLS = [
  {
    id: 'shanmen',
    name: '山门',
    x: 49,
    y: 87,
    w: 26,
    h: 16,
    symbol: '门',
    image: 'images/shanmen.png',
    position: '寺院正面入口，中轴线最前方。',
    deities: '常见哼哈二将、护法像等配置，因寺院传统而异。',
    function: '正式入寺之门，区分寺院内外空间。',
    meaning: '象征由俗入圣，由尘劳进入清净道场。',
    summary: '山门是寺院的正式门户，也是参访者进入佛教道场的第一重空间。',
    intro: '汉传寺院常以山门作为中轴线起点。古寺多建于山林，故称山门。山门不只是建筑入口，也带有礼仪与象征意义，提示来者收摄身心，进入清净庄严的修学空间。'
  },
  {
    id: 'tianwang',
    name: '天王殿',
    x: 50,
    y: 69,
    w: 19,
    h: 14,
    symbol: '天',
    image: 'images/tianwang.png',
    images: ['images/tianwang1.png', 'images/tianwang.png', 'images/tianwang3.png'],
    imageLink: 'weituo.html',
    position: '山门之后，大雄宝殿之前，中轴线前段。',
    deities: '弥勒菩萨、韦驮菩萨、四大天王。',
    function: '护持道场，接引大众，形成入寺后的第一重正殿。',
    meaning: '欢喜接引、护持正法、守护东西南北。',
    summary: '天王殿通常是进入山门后看到的第一座重要殿堂。',
    intro: '天王殿多供奉弥勒菩萨与四大天王，背后常供韦驮菩萨。弥勒代表欢喜与未来成佛的愿景，四大天王代表守护世间与护持佛法，韦驮象征护法护僧。'
  },
  {
    id: 'daxiong',
    name: '大雄宝殿',
    x: 50,
    y: 51,
    w: 22,
    h: 16,
    symbol: '佛',
    image: 'images/daxiong.png',
    imageLink: 'qianshou.html',
    position: '寺院中轴线核心位置。',
    deities: '释迦牟尼佛，或三世佛、三身佛等，依寺院传统而异。',
    function: '礼佛、诵经、法会与大众修学的中心。',
    meaning: '“大雄”指佛陀圆满降伏烦恼魔障的大勇猛。',
    summary: '大雄宝殿是汉传寺院最核心的主殿。',
    intro: '大雄宝殿是寺院空间与信仰的中心，常用于礼佛、诵经、法会和讲经。不同寺院供奉组合可能不同，但核心都在于表达佛陀觉悟、慈悲与教法住世。'
  },
  {
    id: 'cangjing',
    name: '藏经楼',
    x: 50,
    y: 33,
    w: 24,
    h: 16,
    symbol: '经',
    image: 'images/cangjing.png',
    position: '中轴线后部，常在主殿之后。',
    deities: '以收藏经籍为主，也可安置佛像、经橱、祖师像。',
    function: '收藏、供奉、研读佛教经典。',
    meaning: '象征法宝住世、教法流传。',
    summary: '藏经楼代表佛法经典的保存与传承。',
    intro: '藏经楼通常位于寺院较后方，具有安置经藏、保存法宝的意义。对于讲学型或修学型寺院，藏经楼也象征闻思修学与佛教文献传统。'
  },
  {
    id: 'futu',
    name: '七级浮屠',
    x: 50.5,
    y: 12,
    w: 6,
    h: 20,
    symbol: '塔',
    image: 'images/futu.png',
    position: '寺院后部或高处，作为塔院或纪念性建筑。',
    deities: '常用于供奉舍利、经典或纪念高僧。',
    function: '礼敬、纪念、绕塔修行与空间标识。',
    meaning: '象征佛法层层增上、功德庄严。',
    summary: '七级浮屠是寺院中具有纪念、礼敬与导向意义的塔式建筑。',
    intro: '佛塔在寺院中常承担纪念、礼敬和空间标识功能。“救人一命，胜造七级浮屠”的俗语也让七级塔成为大众熟悉的佛教意象。参访时可把塔理解为佛法传承与功德积累的象征。'
  }, 
  {
    id: 'chanlingudao',
    name: '禅林古道',
    x: 56,
    y: 17,
    w: 6,
    h: 7,
    symbol: '道',
    image: 'images/chanlingudao.png',
    position: '寺院后部或高处，作为塔院或纪念性建筑。',
    deities: '常用于供奉舍利、经典或纪念高僧。',
    function: '礼敬、纪念、绕塔修行与空间标识。',
    meaning: '象征佛法层层增上、功德庄严。',
    summary: '七级浮屠是寺院中具有纪念、礼敬与导向意义的塔式建筑。',
    intro: '佛塔在寺院中常承担纪念、礼敬和空间标识功能。“救人一命，胜造七级浮屠”的俗语也让七级塔成为大众熟悉的佛教意象。参访时可把塔理解为佛法传承与功德积累的象征。'
  },
  {
    id: 'gulou',
    name: '鼓楼',
    x: 14,
    y: 84,
    w: 9,
    h: 20,
    symbol: '鼓',
    image: 'images/gulou.png',
    sound: 'music/gusheng_2s.mp3',
    soundLabel: '点击鼓楼图片播放鼓声',
    soundHotspot: { x: 50, y: 47, w: 8, h: 12 },
    position: '山门两侧，与钟楼成对。',
    deities: '一般为功能性建筑，不以佛菩萨供奉为核心。',
    function: '击鼓报时、集众、配合法会仪轨。',
    meaning: '钟鼓相应，表示寺院日常秩序与法事节奏。',
    summary: '鼓楼与钟楼相对，是寺院常见的礼仪性建筑。',
    intro: '钟楼、鼓楼通常分列山门或前院两侧，构成对称格局。鼓声用于报时、集众或配合法会，体现寺院生活的时间秩序。'
  },
  {
    id: 'zhonglou',
    name: '钟楼',
    x: 85,
    y: 84,
    w: 9,
    h: 20,
    symbol: '钟',
    image: 'images/zhonglou.png',
    sound: 'music/zhongsheng_2.9s.mp3',
    soundLabel: '点击钟楼图片播放钟声',
    soundHotspot: { x: 50, y: 48, w: 9, h: 16 },
    position: '山门两侧，与鼓楼成对。',
    deities: '一般为功能性建筑，不以佛菩萨供奉为核心。',
    function: '鸣钟报时、警醒大众、配合法会。',
    meaning: '钟声有警策身心、普闻法音的象征。',
    summary: '钟楼是寺院前部常见的对称建筑之一。',
    intro: '寺院钟声具有报时、集众与警策意义。传统中晨钟暮鼓常被视为寺院清净生活的象征，提醒大众觉照无常、精进修学。'
  },
  {
    id: 'guanyin',
    name: '观音殿',
    x: 25,
    y: 75,
    w: 12,
    h: 14,
    symbol: '观',
    image: 'images/guanyin.png',
    position: '侧殿，常位于主轴线两侧院落。',
    deities: '观世音菩萨，常见善财童子、龙女等胁侍。',
    function: '礼敬观世音菩萨，表达慈悲救苦的信仰。',
    meaning: '慈悲、寻声救苦、应机化度。',
    summary: '观音殿是供奉观世音菩萨的殿堂。',
    intro: '观世音菩萨在汉传佛教中具有广泛信仰基础，象征大慈大悲、闻声救苦。观音殿常作为信众礼敬、祈愿与学习慈悲精神的重要空间。'
  },
  {
    id: 'xifang',
    name: '西方三圣殿',
    x: 27,
    y: 61,
    w: 11,
    h: 14,
    symbol: '净',
    image: 'images/xifang.png',
    position: '侧殿，常与净土信仰相关。',
    deities: '阿弥陀佛、观世音菩萨、大势至菩萨。',
    function: '净土法门相关礼敬、念佛与修学。',
    meaning: '愿生净土、接引往生、慈悲与智慧辅翼。',
    summary: '西方三圣殿表现净土法门的核心信仰。',
    intro: '西方三圣以阿弥陀佛为主尊，观世音菩萨与大势至菩萨为两胁侍，象征慈悲与智慧共同摄受众生，是净土宗修学中非常重要的造像组合。'
  },
  {
    id: 'zushi',
    name: '祖师殿',
    x: 29,
    y: 49,
    w: 13,
    h: 10,
    symbol: '祖',
    image: 'images/zushi.png',
    position: '侧殿或后部区域，依寺院传承而定。',
    deities: '本寺、本宗历代祖师，或开山祖师。',
    function: '纪念传承祖师，表达法脉相承。',
    meaning: '饮水思源、尊师重道、法脉传续。',
    summary: '祖师殿用于纪念祖师与寺院传承。',
    intro: '祖师殿体现佛教的传承意识。不同宗派、不同祖庭所供奉祖师不同，常用于纪念开山祖师、历代高僧或本宗重要祖师。'
  },
  {
    id: 'wuguan',
    name: '五观堂',
    x: 71,
    y: 49,
    w: 13,
    h: 10,
    symbol: '斋',
    image: 'images/wuguan.png',
    position: '侧院，常与僧众日常生活区相关。',
    deities: '不是以供奉佛菩萨为主。',
    function: '僧众用斋、过堂、修习饮食观照。',
    meaning: '受食时作五种观想，知恩惜福，节制贪欲。',
    summary: '五观堂是寺院用斋与修习饮食观照的场所。',
    intro: '五观堂并非普通餐厅，而是僧众过堂用斋的修行空间。“五观”提醒用食者观察食物来处、德行是否堪受、离贪嗔痴、以食为药、为成道业而受此食。'
  },
  {
    id: 'huayan',
    name: '华严三圣殿',
    x: 72,
    y: 61,
    w: 11,
    h: 14,
    symbol: '严',
    image: 'images/huayan.png',
    position: '侧殿，常见于重视华严思想或综合性大寺。',
    deities: '毗卢遮那佛、文殊菩萨、普贤菩萨。',
    function: '礼敬华严三圣，介绍华严思想与菩萨行。',
    meaning: '法界圆融、智慧与行愿。',
    summary: '华严三圣殿表现华严思想中的佛境界与菩萨行。',
    intro: '华严三圣通常以毗卢遮那佛为主尊，文殊菩萨象征智慧，普贤菩萨象征行愿。此组合强调佛法界的圆融与菩萨实践。'
  },
  {
    id: 'dizang',
    name: '地藏殿',
    x: 74,
    y: 75,
    w: 12,
    h: 14,
    symbol: '藏',
    image: 'images/dizang.png',
    position: '侧殿，常位于主轴线两侧院落。',
    deities: '地藏菩萨，常见闵公、道明等胁侍配置。',
    function: '礼敬地藏菩萨，表达孝亲、度亡与大愿精神。',
    meaning: '大愿、孝道、救拔幽冥苦难。',
    summary: '地藏殿是供奉地藏菩萨的殿堂。',
    intro: '地藏菩萨以“大愿”著称，在汉传佛教中与孝道、救拔苦难、度亡超荐等信仰密切相关。地藏殿常提醒大众发愿、尽孝、修善。'
  }
];
